name: ci

on:
  pull_request:
    branches: ["dev","qa","uat","prod"]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          IMAGE_TAG: latest
          IMG_REPO: hello-world-service
          REGISTRY: ${{ env.REGISTRY }}/${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMG_REPO }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t ${{ env.IMG_REPO }} .
          docker tag ${{ env.IMG_REPO }}:latest ${{ env.REGISTRY }}:${{IMAGE_TAG}}
          docker push ${{ env.REGISTRY }}:${{IMAGE_TAG}}
          echo "::set-output name=image::${{ env.REGISTRY }}:${{IMAGE_TAG}}"
