name: ci

on:
  pull_request:
    branches: ["dev","qa","uat","prod"]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build, tag, and push image to docker hub
        id: build-image
        env:
          IMG_REPO: ${{ vars.REPOSITORY }}
          REGISTRY: ${{ vars.REGISTRY }}/${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.REPOSITORY }}:latest
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $IMG_REPO .
          docker tag $IMG_REPO:latest $REGISTRY
          docker push $REGISTRY
          echo "::set-output name=image::$REGISTRY"
          echo "{image}={$REGISTRY}" >> $GITHUB_OUTPUT
