name: ci

on:
  schedule:
    - cron: "0 10 * * *"
  pull_request:
    branches: ["master", "uat", "qa","dev"]
    tags:
      - "v*.*.*"
      - "pr*.*.*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        if: github.event_name == 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name == 'pull_request' }}
          tags: ${{env.IMG_REPOSITORY}}:latest
