name: ci

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          IMAGE_TAG: lts-${{ github.run_id }}-${{ github.run_number }}-${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t hello-world-service .
          docker tag hello-world-service:latest ${{ env.REGISTRY }}/${{ secrets.DOCKER_HUB_USERNAME }}/hello-world-service:${IMAGE_TAG}
          docker push ${{ env.REGISTRY }}/${{ secrets.DOCKER_HUB_USERNAME }}/hello-world-service:${IMAGE_TAG}
          echo "::set-output name=image::${{ env.REGISTRY }}/${{ secrets.DOCKER_HUB_USERNAME }}/hello-world-service:${IMAGE_TAG}"
